HH-184574 : Migration to jakarta
hhru/public-pom pull request #26
Opened 2023-06-30 09:33 UTC by vbazhmin

2023-07-06 06:25 UTC, pvorlov commented on pom.xml
> +    <version>1.54.1-VB-SNAPSHOT</version>
незабудка

2023-07-06 06:39 UTC, pvorlov requested changes

2023-07-06 06:39 UTC, pvorlov commented on pom.xml
> +                <groupId>jakarta.annotation</groupId>
Зачем дублировать то, что и так есть в бутовом помнике?
Предлагаю удалить.

2023-07-06 06:39 UTC, pvorlov commented on pom.xml
> +                <artifactId>jakarta.jax</artifactId>
А откуда у нас гарантии, что у этого артефакта и jakarta.xml.bind-api одинаковые версии?

2023-07-06 08:22 UTC, vbazhmin commented on pom.xml
> +                <groupId>jakarta.annotation</groupId>
Вынес в случае если пришлось бы что-то переопределять, сейчас можно удалить

2023-07-06 08:22 UTC, vbazhmin commented on pom.xml
> +                <artifactId>jakarta.jax</artifactId>
Они могут быть разными, главное что совместимые

2023-07-06 09:33 UTC, nicholasgribanov commented on pom.xml
> +                <version>2.0.1</version>
версию в переменочку давай, чтобы в одном стиле было.

2023-07-06 09:57 UTC, nicholasgribanov commented on pom.xml
> +    <version>1.54.1-VB-SNAPSHOT</version>
твой любимый цветок

2023-07-06 10:13 UTC, nicholasgribanov approved these changes

2023-07-06 10:20 UTC, heruv1m approved these changes

2023-07-07 08:19 UTC, pvorlov commented on pom.xml
> +                <artifactId>jakarta.jax</artifactId>
Если они идеалогически разные (не используют обший репозиторий или политику версий) то может тогда продублируем переменную у нас?

2023-07-07 08:21 UTC, pvorlov approved these changes

2023-07-07 08:22 UTC, pvorlov commented on pom.xml
> +                <artifactId>jakarta.jax</artifactId>
увидел что уже неактуально

2023-07-13 08:54 UTC, vbazhmin commented
squashed commits and rebased to master

2023-07-13 08:56 UTC, merged